apiVersion: v1
kind: Service
metadata:
  name: anomaly-detection-service
spec:
  selector:
    app: anomaly-detection
  ports:
    - protocol: "TCP"
      port: 6000
      targetPort: 8181
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: anomaly-detection
spec:
  selector:
    matchLabels:
      app: anomaly-detection
  replicas: 3
  template:
    metadata:
      labels:
        app: anomaly-detection
    spec:
      containers:
        - name: anomaly-detection
          image: tarexme/anomaly-detection:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8181
